[package]
name = "navmesh-pathfinding-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

# WASM tooling
wasm-bindgen = "0.2.92"
zerocopy = "0.8"
zerocopy-derive = "0.8"

# ECS
hecs = "0.10.5"

# Std hashmap replacement
fnv = "1.0.7"
