[package]
name = "local-server"
version = "0.1.0"
edition = "2021"

[features]
default = ["watch"]
watch = ["notify"]

[dependencies]
rouille = "3.6.2"
glob = "0.3.2"

notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"], optional = true }
